name: flutter_advertising_id
description: Flutter plugin for Android and IOS, a cross-platform to get
  Advertising id that is GAID for android and IDFA for ios.
version: 1.0.3
homepage: https://github.com/iamatulkumar/flutter_advertising_id

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: